apiVersion: v1
data:
  MessageBroker__ConnectionString: aG9zdD1yYWJiaXRtcS5pbmZyYS5zdmMuY2x1c3Rlci5sb2NhbDo1NjcyO3B1Ymxpc2hlckNvbmZpcm1zPXRydWU7dGltZW91dD0zMDt1c2VybmFtZT1uZXJkc3RvcmU7cGFzc3dvcmQ9bmVyZHN0b3Jl
  MessageBroker__Provider: UmFiYml0TXE=
kind: Secret
metadata:
  creationTimestamp: null
  name: rabbit-connection
  namespace: nerdstore
