apiVersion: v1
data:
  CUSTOMCONNSTR_DefaultConnection: U2VydmVyPXNxbHNlcnZlci5pbmZyYS5zdmMuY2x1c3Rlci5sb2NhbCwxNDMzO0RhdGFiYXNlPURCT3JkZXI7VXNlciBJZD1zYTtQYXNzd29yZD1NeURCQDEyMztUcnVzdFNlcnZlckNlcnRpZmljYXRlPVRydWU7
kind: Secret
metadata:
  creationTimestamp: null
  name: order-connection
  namespace: nerdstore
