apiVersion: v1
data:
  CUSTOMCONNSTR_DefaultConnection: U2VydmVyPXBvc3RncmVzcWwuaW5mcmEuc3ZjLmNsdXN0ZXIubG9jYWw7UG9ydD01NDMyO0RhdGFiYXNlPURCVXNlcnM7VXNlciBJZD1wb3N0Z3JlcztQYXNzd29yZD1wb3N0Z3Jlczs=
kind: Secret
metadata:
  creationTimestamp: null
  name: identity-connection
  namespace: nerdstore
