// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NSE.ShoppingCart.API.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NSE.ShoppingCart.API.Migrations
{
    [DbContext(typeof(ShoppingCartContext))]
    [Migration("20260131202620_DbInit")]
    partial class DbInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NSE.ShoppingCart.API.Models.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("ShoppingCartId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ShoppingCartId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("NSE.ShoppingCart.API.Models.CustomerShoppingCart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Discount")
                        .HasColumnType("numeric");

                    b.Property<bool>("HasVoucher")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CustomerId" }, "IDX_Customer");

                    b.ToTable("CustomerShoppingCart");
                });

            modelBuilder.Entity("NSE.ShoppingCart.API.Models.CartItem", b =>
                {
                    b.HasOne("NSE.ShoppingCart.API.Models.CustomerShoppingCart", "CustomerShoppingCart")
                        .WithMany("Items")
                        .HasForeignKey("ShoppingCartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerShoppingCart");
                });

            modelBuilder.Entity("NSE.ShoppingCart.API.Models.CustomerShoppingCart", b =>
                {
                    b.OwnsOne("NSE.ShoppingCart.API.Models.Voucher", "Voucher", b1 =>
                        {
                            b1.Property<Guid>("CustomerShoppingCartId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Code")
                                .HasColumnType("varchar(50)");

                            b1.Property<decimal?>("Discount")
                                .HasColumnType("numeric");

                            b1.Property<int?>("DiscountType")
                                .HasColumnType("integer");

                            b1.Property<decimal?>("Percentage")
                                .HasColumnType("numeric");

                            b1.HasKey("CustomerShoppingCartId");

                            b1.ToTable("CustomerShoppingCart");

                            b1.WithOwner()
                                .HasForeignKey("CustomerShoppingCartId");
                        });

                    b.Navigation("Voucher")
                        .IsRequired();
                });

            modelBuilder.Entity("NSE.ShoppingCart.API.Models.CustomerShoppingCart", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
