apiVersion: v1
data:
  CUSTOMCONNSTR_DefaultConnection: U2VydmVyPXBvc3RncmVzcWwuaW5mcmEuc3ZjLmNsdXN0ZXIubG9jYWw7UG9ydD01NDMyO0RhdGFiYXNlPURCY2FydDtVc2VyIElkPXBvc3RncmVzO1Bhc3N3b3JkPXBvc3RncmVzOw==
kind: Secret
metadata:
  creationTimestamp: null
  name: cart-connection
  namespace: nerdstore
