apiVersion: v1
data:
  CUSTOMCONNSTR_DefaultConnection: U2VydmVyPXBvc3RncmVzcWwuaW5mcmEuc3ZjLmNsdXN0ZXIubG9jYWw7UG9ydD01NDMyO0RhdGFiYXNlPURCU3RhdHVzO1VzZXIgSWQ9cG9zdGdyZXM7UGFzc3dvcmQ9cG9zdGdyZXM7
kind: Secret
metadata:
  creationTimestamp: null
  name: status-connection
  namespace: nerdstore
