apiVersion: v1
data:
  CUSTOMCONNSTR_DefaultConnection: U2VydmVyPXBvc3RncmVzcWwuaW5mcmEuc3ZjLmNsdXN0ZXIubG9jYWw7UG9ydD01NDMyO0RhdGFiYXNlPURCQ2F0YWxvZztVc2VyIElkPXBvc3RncmVzO1Bhc3N3b3JkPXBvc3RncmVzOw==
kind: Secret
metadata:
  creationTimestamp: null
  name: catalog-connection
  namespace: nerdstore
